---
name: "lint"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Run markdown-lint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
        # v1.5.0 => 04d43ee9191307b50935a753da3b775ab695eceb
        with:
          config: ".github/linters/.markdown-lint.yml"
          args: "./README.md"

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        # 1.1.0 => 94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
        env:
          SHELLCHECK_OPTS: -e SC2034

  shfmt:
    name: shfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Run shfmt
        uses: luizm/action-sh-checker@883217215b11c1fabbf00eb1a9a041f62d74c744
        # v0.3.0 => 7f44869033b40ee4ffe7dc76c87a1bc66e3d025a
        env:
          SHFMT_OPTS: -l -bn -ci -i 2 -d
        with:
          sh_checker_shellcheck_disable: true

  yamllint:
    name: yamllint
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c
        # v3.0.4 => ed2b6e911569708ed121c14b87d513860a7e36a7
        with:
          config_file: ".github/linters/.yamllint.yml"
